sudo: required
dist: trusty
addons:
  chrome: stable

language: node_js
node_js:
  - '8'

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  # - sudo chown root /opt/google/chrome/chrome-sandbox
  # - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - npm run build:lib
  - npm run build:prod
  - xvfb-run npm run test:lib

after_success:
  - firebase deploy --token $firebase_token

notifications:
  email:
    on_failure: always
    on_success: change
